-- Tabela de Denúncias (Reports)
create table reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references auth.users not null,
  reported_user_id uuid references auth.users, -- Opcional, se for denúncia de usuário
  content_type text not null, -- 'message', 'post', 'user', 'audio_room'
  content_id text, -- ID do conteúdo denunciado
  reason text not null,
  status text default 'pending', -- 'pending', 'reviewed', 'resolved', 'dismissed'
  created_at timestamptz default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users
);

-- Indexes
create index idx_reports_reporter on reports(reporter_id);
create index idx_reports_status on reports(status);

-- RLS Policies
alter table reports enable row level security;

-- Users can create reports
create policy "Users can create reports" on reports
  for insert with check (auth.uid() = reporter_id);

-- Users can view their own reports
create policy "Users can view own reports" on reports
  for select using (auth.uid() = reporter_id);

-- Admins/Moderators would need specific policies, skipping for MVP/Self-moderation context
