-- IA Terapeuta (AI Companion)
-- Tabelas para histórico de chat e sessões

-- ===============================
-- 1. SESSÕES DE CHAT
-- ===============================

create table ai_chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  started_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  summary text, -- Resumo gerado pela IA ao fim da sessão ou periodicamente
  sentiment_score float, -- Score médio de sentimento da sessão (-1.0 a 1.0)
  status text default 'active' check (status in ('active', 'archived', 'completed')),
  title text default 'Nova Conversa'
);

-- Index para listar sessões do usuário rapidamente
create index idx_ai_sessions_user on ai_chat_sessions(user_id, updated_at desc);

-- ===============================
-- 2. MENSAGENS DO CHAT
-- ===============================

create table ai_chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid references ai_chat_sessions on delete cascade not null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  metadata jsonb default '{}'::jsonb -- Para guardar tokens, contexto extra, etc
);

-- Index para carregar mensagens de uma sessão
create index idx_ai_messages_session on ai_chat_messages(session_id, created_at asc);

-- ===============================
-- 3. RLS POLICIES
-- ===============================

-- Sessions
alter table ai_chat_sessions enable row level security;

create policy "Users can view their own sessions" on ai_chat_sessions
  for select using (auth.uid() = user_id);

create policy "Users can create their own sessions" on ai_chat_sessions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own sessions" on ai_chat_sessions
  for update using (auth.uid() = user_id);

create policy "Users can delete their own sessions" on ai_chat_sessions
  for delete using (auth.uid() = user_id);

-- Messages
alter table ai_chat_messages enable row level security;

create policy "Users can view messages from their sessions" on ai_chat_messages
  for select using (
    exists (
      select 1 from ai_chat_sessions
      where id = ai_chat_messages.session_id
      and user_id = auth.uid()
    )
  );

create policy "Users can insert messages to their sessions" on ai_chat_messages
  for insert with check (
    exists (
      select 1 from ai_chat_sessions
      where id = ai_chat_messages.session_id
      and user_id = auth.uid()
    )
  );

-- ===============================
-- 4. TRIGGERS
-- ===============================

-- Atualizar updated_at da sessão quando nova mensagem é inserida
create or replace function update_session_timestamp()
returns trigger
language plpgsql
as $$
begin
  update ai_chat_sessions
  set updated_at = now()
  where id = NEW.session_id;
  return NEW;
end;
$$;

create trigger update_session_timestamp_trigger
after insert on ai_chat_messages
for each row
execute function update_session_timestamp();
