-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Studies table moved to separate migration

-- Create a table for daily logs (mood tracking, journal)
create table daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  mood text, -- e.g., 'Happy', 'Sad', 'Anxious'
  notes text,
  tags text[]
);

alter table daily_logs enable row level security;

create policy "Users can view their own daily logs." on daily_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own daily logs." on daily_logs
  for insert with check (auth.uid() = user_id);

-- Create a table for goals
create table goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  is_completed boolean default false,
  target_date date
);

alter table goals enable row level security;

create policy "Users can view their own goals." on goals
  for select using (auth.uid() = user_id);

create policy "Users can insert their own goals." on goals
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own goals." on goals
  for update using (auth.uid() = user_id);
