-- Módulo LibertaMente Completo

-- Perfis de vícios dos usuários
create table addiction_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  addiction_type text not null, -- 'alcohol', 'drugs', 'smoking', 'pornography', 'other'
  severity_level int check (severity_level between 1 and 5), -- 1 = leve, 5 = grave
  start_date date,
  goal_type text, -- 'abstinence', 'reduction', 'moderation'
  confidential_mode boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Avaliações periódicas
create table addiction_assessments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  assessment_date timestamp with time zone default timezone('utc'::text, now()) not null,
  severity_score int check (severity_score between 1 and 10),
  confidence_level int check (confidence_level between 1 and 10),
  notes text,
  triggers_identified text[]
);

-- Metas de redução/abstinência
create table addiction_goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  goal_description text not null,
  target_date date,
  target_type text not null, -- 'days_clean', 'reduction_percentage', 'frequency'
  target_value int not null,
  current_progress int default 0,
  status text default 'active', -- 'active', 'completed', 'failed', 'paused'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone
);

-- Diário de gatilhos e situações de risco
create table trigger_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  trigger_type text not null, -- 'emotional', 'social', 'environmental', 'physical'
  description text not null,
  intensity int check (intensity between 1 and 10),
  coping_strategy_used text,
  outcome text, -- 'resisted', 'relapsed', 'delayed'
  learned_lesson text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Contador de dias limpo
create table clean_streaks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  addiction_type text not null,
  current_days int default 0,
  longest_streak int default 0,
  last_clean_date date,
  last_relapse_date date,
  total_relapses int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, addiction_type)
);

-- Ferramentas de emergência usadas
create table emergency_tool_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  tool_type text not null, -- 'breathing', 'distraction', 'contact_support', 'meditation'
  situation_context text,
  effectiveness_rating int check (effectiveness_rating between 1 and 5),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Contatos de apoio
create table support_contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  contact_name text not null,
  contact_type text not null, -- 'friend', 'family', 'therapist', 'sponsor', 'hotline'
  phone_number text,
  availability text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table addiction_profiles enable row level security;
alter table addiction_assessments enable row level security;
alter table addiction_goals enable row level security;
alter table trigger_logs enable row level security;
alter table clean_streaks enable row level security;
alter table emergency_tool_usage enable row level security;
alter table support_contacts enable row level security;

-- RLS Policies (confidenciais - apenas o próprio usuário)
create policy "Users can view their own addiction profile" on addiction_profiles
  for select using (auth.uid() = user_id);
create policy "Users can insert their own addiction profile" on addiction_profiles
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own addiction profile" on addiction_profiles
  for update using (auth.uid() = user_id);

create policy "Users can view their own assessments" on addiction_assessments
  for select using (auth.uid() = user_id);
create policy "Users can insert their own assessments" on addiction_assessments
  for insert with check (auth.uid() = user_id);

create policy "Users can view their own goals" on addiction_goals
  for select using (auth.uid() = user_id);
create policy "Users can insert their own goals" on addiction_goals
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own goals" on addiction_goals
  for update using (auth.uid() = user_id);

create policy "Users can view their own trigger logs" on trigger_logs
  for select using (auth.uid() = user_id);
create policy "Users can insert their own trigger logs" on trigger_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can view their own clean streaks" on clean_streaks
  for select using (auth.uid() = user_id);
create policy "Users can insert their own clean streaks" on clean_streaks
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own clean streaks" on clean_streaks
  for update using (auth.uid() = user_id);

create policy "Users can view their own emergency tool usage" on emergency_tool_usage
  for select using (auth.uid() = user_id);
create policy "Users can insert their own emergency tool usage" on emergency_tool_usage
  for insert with check (auth.uid() = user_id);

create policy "Users can view their own support contacts" on support_contacts
  for select using (auth.uid() = user_id);
create policy "Users can insert their own support contacts" on support_contacts
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own support contacts" on support_contacts
  for update using (auth.uid() = user_id);
create policy "Users can delete their own support contacts" on support_contacts
  for delete using (auth.uid() = user_id);

-- Função para atualizar clean streak
create or replace function update_clean_streak(
  p_user_id uuid,
  p_addiction_type text,
  p_is_relapse boolean default false
)
returns void
language plpgsql
security definer
as $$
declare
  v_streak record;
  v_today date := current_date;
begin
  -- Buscar streak atual
  select * into v_streak from clean_streaks 
  where user_id = p_user_id and addiction_type = p_addiction_type;
  
  if not found then
    -- Criar novo streak
    insert into clean_streaks (user_id, addiction_type, current_days, longest_streak, last_clean_date)
    values (p_user_id, p_addiction_type, 1, 1, v_today);
  elsif p_is_relapse then
    -- Resetar streak por recaída
    update clean_streaks
    set current_days = 0,
        last_relapse_date = v_today,
        total_relapses = total_relapses + 1,
        updated_at = now()
    where user_id = p_user_id and addiction_type = p_addiction_type;
  else
    -- Incrementar streak
    update clean_streaks
    set current_days = current_days +  1,
        longest_streak = greatest(longest_streak, current_days + 1),
        last_clean_date = v_today,
        updated_at = now()
    where user_id = p_user_id and addiction_type = p_addiction_type;
  end if;
end;
$$;

-- Função para analisar triggers mais comuns
create or replace function get_common_triggers(p_user_id uuid, p_limit int default 5)
returns table(trigger_type text, count bigint, avg_intensity numeric)
language sql
security definer
as $$
  select 
    trigger_type,
    count(*) as count,
    round(avg(intensity), 1) as avg_intensity
  from trigger_logs
  where user_id = p_user_id
  group by trigger_type
  order by count desc
  limit p_limit;
$$;
