-- Create studies table
create table studies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  icon_name text, -- e.g., 'BookOpen'
  color text, -- e.g., 'bg-emerald-500'
  glow text -- e.g., 'shadow-[...]'
);

-- Create lessons table
create table lessons (
  id bigint generated by default as identity primary key,
  study_id bigint references studies(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  duration text, -- e.g., '10 min'
  type text, -- e.g., 'video', 'text'
  order_index integer default 0
);

-- Create study_progress table
create table study_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  lesson_id bigint references lessons(id) on delete cascade not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, lesson_id)
);

-- Enable RLS
alter table studies enable row level security;
alter table lessons enable row level security;
alter table study_progress enable row level security;

-- RLS Policies
create policy "Studies are viewable by everyone." on studies for select using (true);
create policy "Lessons are viewable by everyone." on lessons for select using (true);

create policy "Users can view their own progress." on study_progress
  for select using (auth.uid() = user_id);

create policy "Users can insert their own progress." on study_progress
  for insert with check (auth.uid() = user_id);

-- Seed Data
insert into studies (title, description, icon_name, color, glow) values
('Biologia Básica', 'Entenda os fundamentos da vida.', 'BookOpen', 'bg-emerald-500', 'shadow-[0_0_20px_rgba(16,185,129,0.3)]'),
('Filosofia Estoica', 'A arte de viver bem.', 'BookOpen', 'bg-amber-500', 'shadow-[0_0_20px_rgba(245,158,11,0.3)]'),
('Finanças Pessoais', 'Organize sua vida financeira.', 'BookOpen', 'bg-blue-500', 'shadow-[0_0_20px_rgba(59,130,246,0.3)]');

-- Seed Lessons (using subqueries to get study IDs)
do $$
declare
  bio_id bigint;
  phil_id bigint;
  fin_id bigint;
begin
  select id into bio_id from studies where title = 'Biologia Básica';
  select id into phil_id from studies where title = 'Filosofia Estoica';
  select id into fin_id from studies where title = 'Finanças Pessoais';

  insert into lessons (study_id, title, duration, type, order_index) values
  (bio_id, 'A Célula', '10 min', 'video', 1),
  (bio_id, 'DNA e RNA', '15 min', 'text', 2),
  (phil_id, 'O que depende de nós', '12 min', 'video', 1),
  (phil_id, 'Amor Fati', '8 min', 'text', 2),
  (fin_id, 'Orçamento Básico', '20 min', 'video', 1),
  (fin_id, 'Reserva de Emergência', '15 min', 'text', 2);
end $$;
