-- Social Hub Avançado

-- Comentários em posts
create table post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  username text not null,
  avatar_url text,
  content text not null,
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Curtidas em posts (para tracking detalhado)
create table post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id)
);

-- Curtidas em comentários
create table comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint references post_comments(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
   unique(comment_id, user_id)
);

-- Sistema de seguidores
create table user_follows (
  id bigint generated by default as identity primary key,
  follower_id uuid references auth.users not null,
  following_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(follower_id, following_id),
  check (follower_id != following_id)
);

-- Compartilhamentos de posts
create table post_shares (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  shared_with text, -- 'public', 'followers', 'direct'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Denúncias de conteúdo
create table content_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references auth.users not null,
  content_type text not null, -- 'post', 'comment'
  content_id bigint not null,
  reason text not null, -- 'spam', 'harassment', 'inappropriate', 'other'
  description text,
  status text default 'pending', -- 'pending', 'reviewed', 'resolved'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table post_comments enable row level security;
alter table post_likes enable row level security;
alter table comment_likes enable row level security;
alter table user_follows enable row level security;
alter table post_shares enable row level security;
alter table content_reports enable row level security;

-- RLS Policies
create policy "Comments are viewable by everyone" on post_comments
  for select using (true);
create policy "Users can create comments" on post_comments
  for insert with check (auth.uid() = user_id);
create policy "Users can delete their own comments" on post_comments
  for delete using (auth.uid() = user_id);

create policy "Post likes are viewable by everyone" on post_likes
  for select using (true);
create policy "Users can like posts" on post_likes
  for insert with check (auth.uid() = user_id);
create policy "Users can unlike posts" on post_likes
  for delete using (auth.uid() = user_id);

create policy "Comment likes are viewable by everyone" on comment_likes
  for select using (true);
create policy "Users can like comments" on comment_likes
  for insert with check (auth.uid() = user_id);
create policy "Users can unlike comments" on comment_likes
  for delete using (auth.uid () = user_id);

create policy "Follows are viewable by everyone" on user_follows
  for select using (true);
create policy "Users can follow others" on user_follows
  for insert with check (auth.uid() = follower_id);
create policy "Users can unfollow" on user_follows
  for delete using (auth.uid() = follower_id);

create policy "Shares are viewable by everyone" on post_shares
  for select using (true);
create policy "Users can share posts" on post_shares
  for insert with check (auth.uid() = user_id);

create policy "Users can create reports" on content_reports
  for insert with check (auth.uid() = reporter_id);
create policy "Users can view their own reports" on content_reports
  for select using (auth.uid() = reporter_id);

-- Trigger para atualizar contador de comentários no post
create or replace function update_post_comments_count()
returns trigger
language plpgsql
security definer
as $$
begin
  if TG_OP = 'INSERT' then
    update posts set comments = comments + 1 where id = NEW.post_id;
  elsif TG_OP = 'DELETE' then
    update posts set comments = comments - 1 where id = OLD.post_id;
  end if;
  return null;
end;
$$;

create trigger post_comments_count_trigger
after insert or delete on post_comments
for each row execute function update_post_comments_count();

-- Trigger para atualizar contador de likes no post
create or replace function update_post_likes_count()
returns trigger
language plpgsql
security definer
as $$
begin
  if TG_OP = 'INSERT' then
    update posts set likes = likes + 1 where id = NEW.post_id;
    -- Notificar dono do post (futuramente)
  elsif TG_OP = 'DELETE' then
    update posts set likes = likes - 1 where id = OLD.post_id;
  end if;
  return null;
end;
$$;

create trigger post_likes_count_trigger
after insert or delete on post_likes
for each row execute function update_post_likes_count();

-- Trigger para atualizar contador de likes no comentário
create or replace function update_comment_likes_count()
returns trigger
language plpgsql
security definer
as $$
begin
  if TG_OP = 'INSERT' then
    update post_comments set likes = likes + 1 where id = NEW.comment_id;
  elsif TG_OP = 'DELETE' then
    update post_comments set likes = likes - 1 where id = OLD.comment_id;
  end if;
  return null;
end;
$$;

create trigger comment_likes_count_trigger
after insert or delete on comment_likes
for each row execute function update_comment_likes_count();

-- Função para obter feed personalizado (posts de quem você segue + seus próprios)
create or replace function get_personalized_feed(p_user_id uuid, p_limit int default 20)
returns table(
  id bigint,
  user_id uuid,
  username text,
  avatar_url text,
  content text,
  likes int,
  comments int,
  created_at timestamp with time zone,
  is_liked boolean,
  is_own_post boolean
)
language sql
security definer
as $$
  select 
    p.id,
    p.user_id,
    p.username,
    p.avatar_url,
    p.content,
    p.likes,
    p.comments,
    p.created_at,
    exists(select 1 from post_likes pl where pl.post_id = p.id and pl.user_id = p_user_id) as is_liked,
    p.user_id = p_user_id as is_own_post
  from posts p
  where p.user_id = p_user_id
     or p.user_id in (select following_id from user_follows where follower_id = p_user_id)
  order by p.created_at desc
  limit p_limit;
$$;
