-- Rodas de Conversa (Áudio Spaces)
-- Tabelas para gerenciamento de salas de áudio

-- ===============================
-- 1. SALAS DE ÁUDIO
-- ===============================

create table audio_rooms (
  id uuid default gen_random_uuid() primary key,
  community_id bigint references communities on delete cascade, -- Pode ser null se for sala pública global
  host_id uuid references auth.users not null,
  title text not null,
  description text,
  is_active boolean default true,
  started_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ended_at timestamp with time zone,
  max_participants int default 50,
  
  -- Configurações
  allow_listeners_to_speak boolean default false, -- Se true, qualquer um pode abrir mic. Se false, precisa pedir permissão.
  recording_enabled boolean default false
);

create index idx_audio_rooms_active on audio_rooms(is_active, community_id);

-- ===============================
-- 2. PARTICIPANTES DA SALA
-- ===============================

create table audio_participants (
  id bigint generated by default as identity primary key,
  room_id uuid references audio_rooms on delete cascade not null,
  user_id uuid references auth.users not null,
  role text default 'listener' check (role in ('host', 'speaker', 'listener')),
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  left_at timestamp with time zone,
  
  -- Status
  is_muted boolean default true,
  is_speaking boolean default false, -- Flag para UI (atualizado via realtime)
  raised_hand boolean default false, -- Pedindo para falar
  
  unique(room_id, user_id) -- Usuário só pode estar 1x na sala
);

create index idx_audio_participants_room on audio_participants(room_id, left_at);

-- ===============================
-- 3. RLS POLICIES
-- ===============================

-- Audio Rooms
alter table audio_rooms enable row level security;

create policy "Anyone can view active rooms" on audio_rooms
  for select using (is_active = true);

create policy "Users can create rooms" on audio_rooms
  for insert with check (auth.uid() = host_id);

create policy "Hosts can update their rooms" on audio_rooms
  for update using (auth.uid() = host_id);

-- Audio Participants
alter table audio_participants enable row level security;

create policy "Anyone can view participants" on audio_participants
  for select using (true);

create policy "Users can join rooms" on audio_participants
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own status" on audio_participants
  for update using (auth.uid() = user_id);

create policy "Hosts can manage participants" on audio_participants
  for update using (
    exists (
      select 1 from audio_rooms
      where id = audio_participants.room_id
      and host_id = auth.uid()
    )
  );
