-- Sistema de Gamificação Completo

-- Tabela de conquistas disponíveis
create table achievements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  icon text not null, -- nome do ícone Lucide
  category text not null, -- 'meditation', 'study', 'social', 'streak', 'general'
  requirement_type text not null, -- 'count', 'streak', 'specific'
  requirement_value int not null, -- valor necessário para desbloquear
  xp_reward int default 0,
  badge_color text default 'bg-purple-500'
);

-- Conquistas desbloqueadas pelos usuários
create table user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  achievement_id bigint references achievements(id) not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, achievement_id)
);

-- Desafios diários disponíveis
create table daily_challenges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  challenge_type text not null, -- 'meditation', 'study', 'post', 'mood_check'
  target_value int not null, -- quantas vezes fazer
  xp_reward int default 50,
  active_date date not null, -- data em que o desafio está ativo
  icon text not null
);

-- Progresso dos usuários em desafios
create table user_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  challenge_id bigint references daily_challenges(id) not null,
  current_progress int default 0,
  completed boolean default false,
  completed_at timestamp with time zone,
  unique(user_id, challenge_id)
);

-- Sequências de uso (streaks)
create table user_streaks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  current_streak int default 0,
  longest_streak int default 0,
  last_activity_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Histórico de XP ganho
create table xp_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount int not null,
  source text not null, -- 'meditation', 'study', 'post', 'challenge', 'achievement'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table achievements enable row level security;
alter table user_achievements enable row level security;
alter table daily_challenges enable row level security;
alter table user_challenges enable row level security;
alter table user_streaks enable row level security;
alter table xp_history enable row level security;

-- RLS Policies
create policy "Achievements are viewable by everyone" on achievements for select using (true);

create policy "Users can view their own achievements" on user_achievements 
  for select using (auth.uid() = user_id);
create policy "Users can insert their own achievements" on user_achievements 
  for insert with check (auth.uid() = user_id);

create policy "Daily challenges are viewable by everyone" on daily_challenges 
  for select using (true);

create policy "Users can view their own challenge progress" on user_challenges 
  for select using (auth.uid() = user_id);
create policy "Users can insert their own challenge progress" on user_challenges 
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own challenge progress" on user_challenges 
  for update using (auth.uid() = user_id);

create policy "Users can view their own streak" on user_streaks 
  for select using (auth.uid() = user_id);
create policy "Users can insert their own streak" on user_streaks 
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own streak" on user_streaks 
  for update using (auth.uid() = user_id);

create policy "Users can view their own XP history" on xp_history 
  for select using (auth.uid() = user_id);
create policy "Users can insert their own XP history" on xp_history 
  for insert with check (auth.uid() = user_id);

-- Seed conquistas iniciais
insert into achievements (title, description, icon, category, requirement_type, requirement_value, xp_reward, badge_color) values
('Primeiro Passo', 'Complete seu primeiro registro de humor', 'Heart', 'general', 'count', 1, 10, 'bg-pink-500'),
('Meditador Iniciante', 'Complete sua primeira meditação', 'Brain', 'meditation', 'count', 1, 20, 'bg-purple-500'),
('Estudante Dedicado', 'Complete sua primeira lição', 'BookOpen', 'study', 'count', 1, 15, 'bg-blue-500'),
('Social Butterfly', 'Faça seu primeiro post', 'MessageCircle', 'social', 'count', 1, 10, 'bg-green-500'),
('Sequência de 3', 'Mantenha uma sequência de 3 dias', 'Flame', 'streak', 'streak', 3, 30, 'bg-orange-500'),
('Sequência de 7', 'Mantenha uma sequência de 7 dias', 'Flame', 'streak', 'streak', 7, 70, 'bg-orange-600'),
('Sequência de 30', 'Mantenha uma sequência de 30 dias', 'Flame', 'streak', 'streak', 30, 300, 'bg-red-500'),
('Zen Master', 'Complete 10 meditações', 'Brain', 'meditation', 'count', 10, 100, 'bg-purple-600'),
('Conhecimento é Poder', 'Complete 10 lições', 'BookOpen', 'study', 'count', 10, 100, 'bg-blue-600'),
('Influenciador', 'Receba 50 curtidas em seus posts', 'Heart', 'social', 'count', 50, 150, 'bg-pink-600'),
('Desafiador', 'Complete 5 desafios diários', 'Target', 'general', 'count', 5, 100, 'bg-yellow-500'),
('Guerreiro da Mente', 'Complete 30 meditações', 'Brain', 'meditation', 'count', 30, 300, 'bg-purple-700'),
('Mestre do Conhecimento', 'Complete 30 lições', 'BookOpen', 'study', 'count', 30, 300, 'bg-blue-700'),
('Comunidade Ativa', 'Faça 20 posts', 'MessageCircle', 'social', 'count', 20, 200, 'bg-green-600');

-- Seed desafios diários para hoje
insert into daily_challenges (title, description, challenge_type, target_value, xp_reward, active_date, icon) values
('Meditação Matinal', 'Complete uma meditação hoje', 'meditation', 1, 50, current_date, 'Sunrise'),
('Registre seu Humor', 'Faça um check-in de humor', 'mood_check', 1, 30, current_date, 'Heart'),
('Aprenda Algo Novo', 'Complete uma lição de estudo', 'study', 1, 40, current_date, 'BookOpen'),
('Compartilhe Positividade', 'Faça um post inspirador', 'post', 1, 35, current_date, 'MessageCircle');

-- Função para calcular nível baseado em XP
create or replace function calculate_level(xp_amount int)
returns int
language plpgsql
as $$
begin
  -- Fórmula: level = floor(sqrt(xp / 100))
  -- Nível 1: 0-99 XP
  -- Nível 2: 100-399 XP
  -- Nível 3: 400-899 XP
  -- etc.
  return floor(sqrt(xp_amount / 100.0)) + 1;
end;
$$;

-- Função para adicionar XP e atualizar nível
create or replace function add_user_xp(
  p_user_id uuid,
  p_amount int,
  p_source text,
  p_description text default null
)
returns void
language plpgsql
security definer
as $$
declare
  v_current_xp int;
  v_new_xp int;
  v_new_level int;
begin
  -- Buscar XP atual
  select xp into v_current_xp from profiles where id = p_user_id;
  
  -- Calcular novo XP
  v_new_xp := v_current_xp + p_amount;
  
  -- Calcular novo nível
  v_new_level := calculate_level(v_new_xp);
  
  -- Atualizar perfil
  update profiles 
  set xp = v_new_xp, level = v_new_level
  where id = p_user_id;
  
  -- Registrar no histórico
  insert into xp_history (user_id, amount, source, description)
  values (p_user_id, p_amount, p_source, p_description);
end;
$$;

-- Função para atualizar streak
create or replace function update_user_streak(p_user_id uuid)
returns void
language plpgsql
security definer
as $$
declare
  v_streak record;
  v_today date := current_date;
  v_yesterday date := current_date - interval '1 day';
begin
  -- Buscar streak atual
  select * into v_streak from user_streaks where user_id = p_user_id;
  
  if not found then
    -- Criar novo streak
    insert into user_streaks (user_id, current_streak, longest_streak, last_activity_date)
    values (p_user_id, 1, 1, v_today);
  elsif v_streak.last_activity_date = v_today then
    -- Já fez atividade hoje, não faz nada
    return;
  elsif v_streak.last_activity_date = v_yesterday then
    -- Continua streak
    update user_streaks
    set current_streak = current_streak + 1,
        longest_streak = greatest(longest_streak, current_streak + 1),
        last_activity_date = v_today
    where user_id = p_user_id;
  else
    -- Quebrou streak, reinicia
    update user_streaks
    set current_streak = 1,
        last_activity_date = v_today
    where user_id = p_user_id;
  end if;
end;
$$;

-- Função para verificar e desbloquear conquistas
create or replace function check_and_unlock_achievements(
  p_user_id uuid,
  p_category text,
  p_count int
)
returns void
language plpgsql
security definer
as $$
declare
  v_achievement record;
begin
  -- Buscar conquistas não desbloqueadas que o usuário pode ter alcançado
  for v_achievement in
    select a.* from achievements a
    where a.category = p_category
    and a.requirement_type = 'count'
    and a.requirement_value <= p_count
    and not exists (
      select 1 from user_achievements ua
      where ua.user_id = p_user_id and ua.achievement_id = a.id
    )
  loop
    -- Desbloquear conquista
    insert into user_achievements (user_id, achievement_id)
    values (p_user_id, v_achievement.id);
    
    -- Adicionar XP da recompensa
    perform add_user_xp(p_user_id, v_achievement.xp_reward, 'achievement', v_achievement.title);
  end loop;
end;
$$;
