-- Sistema de Proteção para Adolescentes
-- Contas vinculadas, Análise de bem-estar e Contatos de emergência

-- ===============================
-- 1. TIPOS DE CONTA E IDADE
-- ===============================

-- Adicionar colunas ao profiles
alter table profiles add column if not exists account_type text default 'adult' check (account_type in ('minor', 'adult', 'guardian'));
alter table profiles add column if not exists date_of_birth date;
-- Age será calculado em tempo de execução ou via view para evitar erro de imutabilidade

-- ===============================
-- 2. RELAÇÕES TUTOR-ADOLESCENTE
-- ===============================

create table guardian_relationships (
  id bigint generated by default as identity primary key,
  guardian_id uuid references auth.users not null,
  minor_id uuid references auth.users not null,
  relationship_type text not null check (relationship_type in ('parent', 'legal_guardian', 'therapist', 'other')),
  status text default 'pending' check (status in ('pending', 'active', 'revoked')),
  alert_level text default 'moderate' check (alert_level in ('minimal', 'moderate', 'full')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  unique(guardian_id, minor_id)
);

-- ===============================
-- 3. MÉTRICAS DE BEM-ESTAR
-- ===============================

create table wellness_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null default current_date,
  
  -- Scores (0-100)
  mood_score int check (mood_score >= 0 and mood_score <= 100),
  engagement_score int check (engagement_score >= 0 and engagement_score <= 100),
  risk_score int check (risk_score >= 0 and risk_score <= 100),
  
  -- Atividades
  meditation_minutes int default 0,
  study_sessions int default 0,
  panic_episodes int default 0,
  emergency_tool_uses int default 0,
  
  -- Social
  posts_created int default 0,
  interactions_count int default 0,
  messages_sent int default 0,
  
  -- Análise
  concerning_keywords text[],
  sentiment_analysis text check (sentiment_analysis in ('very_negative', 'negative', 'neutral', 'positive', 'very_positive')),
  
  unique(user_id, date),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index wellness_metrics_user_date_idx on wellness_metrics(user_id, date desc);

-- ===============================
-- 4. ALERTAS PARA TUTORES
-- ===============================

create table guardian_alerts (
  id bigint generated by default as identity primary key,
  guardian_id uuid references auth.users not null,
  minor_id uuid references auth.users not null,
  alert_type text not null check (alert_type in ('wellness_summary', 'concern_detected', 'moderate_risk', 'critical_risk')),
  message text not null,
  details jsonb,
  is_read boolean default false,
  sent_via jsonb default '{"push": false, "email": false, "sms": false}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index guardian_alerts_guardian_idx on guardian_alerts(guardian_id, is_read, created_at desc);

-- ===============================
-- 5. CONTATOS DE EMERGÊNCIA
-- ===============================

create table emergency_contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  contact_name text not null,
  contact_phone text,
  contact_email text,
  relationship text not null check (relationship in ('parent', 'friend', 'therapist', 'sibling', 'other')),
  
  -- Configuração de compartilhamento (controlado pelo usuário)
  sharing_config jsonb default '{
    "wellness_summary": false,
    "mood_alerts": false,
    "panic_episodes": false,
    "emergency_tools_usage": false,
    "critical_risk": true,
    "detailed_content": false
  }'::jsonb,
  
  priority_order int default 1,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ===============================
-- 6. PALAVRAS-CHAVE CRÍTICAS
-- ===============================

create table critical_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  risk_level text not null check (risk_level in ('moderate', 'high', 'critical')),
  category text not null check (category in ('self_harm', 'suicide', 'depression', 'abuse', 'drugs', 'violence')),
  auto_flag boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ===============================
-- 7. CONSENTIMENTOS (LGPD)
-- ===============================

create table guardian_consent (
  id bigint generated by default as identity primary key,
  guardian_id uuid references auth.users not null,
  minor_id uuid references auth.users not null,
  consent_text text not null,
  accepted boolean default false,
  accepted_at timestamp with time zone,
  ip_address inet,
  document_version text default 'v1.0',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table minor_consent (
  id bigint generated by default as identity primary key,
  minor_id uuid references auth.users not null,
  consent_text text not null,
  accepted boolean default false,
  accepted_at timestamp with time zone,
  ip_address inet,
  document_version text default 'v1.0',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ===============================
-- 8. RLS POLICIES
-- ===============================

-- Guardian Relationships
alter table guardian_relationships enable row level security;

create policy "Guardians can view their relationships" on guardian_relationships
  for select using (auth.uid() = guardian_id or auth.uid() = minor_id);

create policy "Minors can create relationship requests" on guardian_relationships
  for insert with check (auth.uid() = minor_id);

create policy "Guardians can approve relationships" on guardian_relationships
  for update using (auth.uid() = guardian_id);

-- Wellness Metrics
alter table wellness_metrics enable row level security;

create policy "Users can view their own metrics" on wellness_metrics
  for select using (auth.uid() = user_id);

create policy "Guardians can view minor metrics" on wellness_metrics
  for select using (
    exists(
      select 1 from guardian_relationships gr
      where gr.minor_id = user_id
      and gr.guardian_id = auth.uid()
      and gr.status = 'active'
    )
  );

create policy "System can insert metrics" on wellness_metrics
  for insert with check (true);

-- Guardian Alerts
alter table guardian_alerts enable row level security;

create policy "Guardians can view their alerts" on guardian_alerts
  for select using (auth.uid() = guardian_id);

create policy "System can create alerts" on guardian_alerts
  for insert with check (true);

create policy "Guardians can mark alerts as read" on guardian_alerts
  for update using (auth.uid() = guardian_id);

-- Emergency Contacts
alter table emergency_contacts enable row level security;

create policy "Users can manage their emergency contacts" on emergency_contacts
  for all using (auth.uid() = user_id);

-- Critical Keywords (apenas moderadores)
alter table critical_keywords enable row level security;

create policy "Moderators can manage critical keywords" on critical_keywords
  for all using (
    exists(
      select 1 from profiles where id = auth.uid() and role in ('moderator', 'admin')
    )
  );

-- Consents
alter table guardian_consent enable row level security;

create policy "Parties can view their consent" on guardian_consent
  for select using (auth.uid() = guardian_id or auth.uid() = minor_id);

alter table minor_consent enable row level security;

create policy "Minor can view their consent" on minor_consent
  for select using (auth.uid() = minor_id);

-- ===============================
-- 9. FUNCTIONS
-- ===============================

-- Calcular score de bem-estar
create or replace function calculate_wellness_score(p_user_id uuid, p_date date default current_date)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_mood_score int := 50;
  v_engagement_score int := 50;
  v_risk_score int := 0;
  v_sentiment text := 'neutral';
  v_keywords text[] := array[]::text[];
begin
  -- 1. Mood Score (baseado em daily_logs últimos 7 dias)
  select 
    coalesce(avg(
      case mood
        when 'very_happy' then 100
        when 'happy' then 80
        when 'neutral' then 50
        when 'sad' then 30
        when 'very_sad' then 10
        else 50
      end
    ), 50)::int
  into v_mood_score
  from daily_logs
  where user_id = p_user_id
  and created_at >= p_date - interval '7 days';
  
  -- 2. Engagement Score (atividades)
  select 
    least(100, (
      coalesce(count(distinct ml.id) * 10, 0) + -- meditações
      coalesce(count(distinct sp.id) * 8, 0) +   -- estudos
      coalesce(count(distinct p.id) * 5, 0) +     -- posts
      coalesce(count(distinct pm.id) * 3, 0)      -- mensagens
    ))::int
  into v_engagement_score
  from profiles prof
  left join meditation_logs ml on ml.user_id = prof.id and ml.created_at >= p_date - interval '7 days'
  left join study_progress sp on sp.user_id = prof.id and sp.completed_at >= p_date - interval '7 days'
  left join posts p on p.user_id = prof.id and p.created_at >= p_date - interval '7 days'
  left join private_messages pm on pm.sender_id = prof.id and pm.created_at >= p_date - interval '7 days'
  where prof.id = p_user_id;
  
  -- 3. Risk Score (múltiplos fatores)
  declare
    v_panic_count int;
    v_emergency_uses int;
  begin
    select count(*) into v_panic_count
    from panic_logs
    where user_id = p_user_id
    and created_at >= p_date - interval '7 days';
    
    select count(*) into v_emergency_uses
    from emergency_tool_usage
    where user_id = p_user_id
    and created_at >= p_date - interval '7 days';
    
    -- Calcular risk score
    v_risk_score := 0;
    
    if v_mood_score < 30 then v_risk_score := v_risk_score + 30; end if;
    if v_engagement_score < 20 then v_risk_score := v_risk_score + 20; end if;
    if v_panic_count > 3 then v_risk_score := v_risk_score + 25; end if;
    if v_emergency_uses > 5 then v_risk_score := v_risk_score + 25; end if;
    
    v_risk_score := least(100, v_risk_score);
  end;
  
  -- Determinar sentimento
  if v_mood_score >= 80 then v_sentiment := 'very_positive';
  elsif v_mood_score >= 60 then v_sentiment := 'positive';
  elsif v_mood_score >= 40 then v_sentiment := 'neutral';
  elsif v_mood_score >= 20 then v_sentiment := 'negative';
  else v_sentiment := 'very_negative';
  end if;
  
  return jsonb_build_object(
    'mood_score', v_mood_score,
    'engagement_score', v_engagement_score,
    'risk_score', v_risk_score,
    'sentiment', v_sentiment,
    'keywords', v_keywords
  );
end;
$$;

-- Verificar palavras-chave críticas em conteúdo
create or replace function check_critical_content(p_content text)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_matched_keywords text[] := array[]::text[];
  v_max_risk text := 'low';
  v_keyword record;
begin
  for v_keyword in 
    select keyword, risk_level from critical_keywords where auto_flag = true
  loop
    if lower(p_content) ~ lower(v_keyword.keyword) then
      v_matched_keywords := array_append(v_matched_keywords, v_keyword.keyword);
      
      if v_keyword.risk_level = 'critical' or v_max_risk = 'critical' then
        v_max_risk := 'critical';
      elsif v_keyword.risk_level = 'high' and v_max_risk != 'critical' then
        v_max_risk := 'high';
      elsif v_keyword.risk_level = 'moderate' and v_max_risk not in ('critical', 'high') then
        v_max_risk := 'moderate';
      end if;
    end if;
  end loop;
  
  return jsonb_build_object(
    'has_critical_content', array_length(v_matched_keywords, 1) > 0,
    'matched_keywords', v_matched_keywords,
    'risk_level', v_max_risk
  );
end;
$$;

-- Enviar alerta para tutor
create or replace function send_guardian_alert(
  p_minor_id uuid,
  p_alert_type text,
  p_message text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
as $$
declare
  v_guardian record;
begin
  for v_guardian in
    select guardian_id, alert_level
    from guardian_relationships
    where minor_id = p_minor_id
    and status = 'active'
  loop
    -- Verificar se deve enviar baseado no alert_level
    if p_alert_type = 'critical_risk' or
       (p_alert_type = 'moderate_risk' and v_guardian.alert_level != 'minimal') or
       (p_alert_type = 'concern_detected' and v_guardian.alert_level = 'full') or
       (p_alert_type = 'wellness_summary' and v_guardian.alert_level in ('moderate', 'full'))
    then
      insert into guardian_alerts (guardian_id, minor_id, alert_type, message, details)
      values (v_guardian.guardian_id, p_minor_id, p_alert_type, p_message, p_details);
      
      -- Criar notificação
      insert into notifications (user_id, type, title, content, reference_type, reference_id)
      values (
        v_guardian.guardian_id,
        'moderation',
        case p_alert_type
          when 'critical_risk' then '⚠️ ALERTA URGENTE'
          when 'moderate_risk' then 'Alerta de Atenção'
          when 'concern_detected' then 'Preocupação Detectada'
          else 'Resumo Semanal'
        end,
        p_message,
        'alert',
        (select id from guardian_alerts order by id desc limit 1)
      );
    end if;
  end loop;
end;
$$;

-- Notificar contatos de emergência
create or replace function notify_emergency_contacts(
  p_user_id uuid,
  p_notification_type text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
as $$
declare
  v_contact record;
  v_message text;
begin
  for v_contact in
    select * from emergency_contacts
    where user_id = p_user_id
    and is_active = true
    and (sharing_config->>p_notification_type)::boolean = true
    order by priority_order
  loop
    -- Criar mensagem baseada no tipo
    v_message := case p_notification_type
      when 'critical_risk' then 'Detectamos sinais de risco grave'
      when 'panic_episodes' then 'Episódio de pânico registrado'
      when 'emergency_tools_usage' then 'Uso de ferramentas de emergência'
      else 'Atualização de bem-estar'
    end;
    
    -- TODO: Enviar via SMS/Email usando serviço externo
    -- Por enquanto, apenas log
    raise notice 'Notifying % (%) about %', v_contact.contact_name, v_contact.contact_email, p_notification_type;
  end loop;
end;
$$;

-- ===============================
-- 10. TRIGGERS
-- ===============================

-- Detectar conteúdo crítico em posts
create or replace function check_post_critical_content()
returns trigger
language plpgsql
as $$
declare
  v_check jsonb;
begin
  v_check := check_critical_content(NEW.content);
  
  if (v_check->>'has_critical_content')::boolean then
    -- Auto-flag
    insert into content_flags (content_type, content_id, reporter_id, flag_type, description, status)
    values (
      'post',
      NEW.id,
      NEW.user_id,
      'offensive',
      'Auto-flagged: ' || (v_check->>'matched_keywords'),
      'pending'
    );
    
    -- Se crítico e usuário é menor, alertar tutor
    if (v_check->>'risk_level') = 'critical' then
      declare
        v_is_minor boolean;
      begin
        select account_type = 'minor' into v_is_minor
        from profiles where id = NEW.user_id;
        
        if v_is_minor then
          perform send_guardian_alert(
            NEW.user_id,
            'critical_risk',
            '⚠️ Conteúdo de risco detectado',
            jsonb_build_object('post_id', NEW.id, 'keywords', v_check->'matched_keywords')
          );
          
          perform notify_emergency_contacts(NEW.user_id, 'critical_risk');
        end if;
      end;
      
      -- Aplicar strike
      perform apply_strike(NEW.user_id, 'Conteúdo crítico detectado automaticamente', null);
    end if;
  end if;
  
  return NEW;
end;
$$;

create trigger check_post_critical_trigger
after insert on posts
for each row
execute function check_post_critical_content();

-- Inserir palavras-chave críticas padrão
insert into critical_keywords (keyword, risk_level, category, auto_flag) values
  ('suicid', 'critical', 'suicide', true),
  ('me matar', 'critical', 'suicide', true),
  ('acabar com tudo', 'high', 'suicide', true),
  ('não aguento mais', 'high', 'depression', true),
  ('sem saída', 'high', 'depression', true),
  ('automutila', 'critical', 'self_harm', true),
  ('me cortar', 'critical', 'self_harm', true),
  ('quero morrer', 'critical', 'suicide', true),
  ('abuso', 'high', 'abuse', true),
  ('machucar', 'moderate', 'violence', false)
on conflict (keyword) do nothing;
