-- Tabela de Perfil do Herói
create table hero_profiles (
  user_id uuid references auth.users not null primary key,
  hero_class text default 'Novico', -- Novico, Guardiao, Sabio, Empata
  level int default 1,
  current_xp int default 0,
  next_level_xp int default 100,
  attributes jsonb default '{"resilience": 1, "wisdom": 1, "empathy": 1, "focus": 1}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Tabela de Missões (Quests)
create table quests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  xp_reward int not null default 10,
  attribute_reward text, -- 'resilience', 'wisdom', etc.
  type text default 'daily', -- 'daily', 'weekly', 'story'
  requirements jsonb, -- ex: {"min_level": 5}
  created_at timestamptz default now()
);

-- Tabela de Missões do Usuário (Progresso)
create table user_quests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  quest_id bigint references quests not null,
  status text default 'active', -- 'active', 'completed'
  progress int default 0,
  completed_at timestamptz,
  created_at timestamptz default now()
);

-- Indexes
create index idx_hero_profiles_user on hero_profiles(user_id);
create index idx_user_quests_user on user_quests(user_id);
create index idx_user_quests_status on user_quests(status);

-- RLS Policies
alter table hero_profiles enable row level security;
alter table quests enable row level security;
alter table user_quests enable row level security;

-- Hero Profile: Users can view and update their own profile
create policy "Users can view own hero profile" on hero_profiles
  for select using (auth.uid() = user_id);

create policy "Users can update own hero profile" on hero_profiles
  for update using (auth.uid() = user_id);

create policy "Users can insert own hero profile" on hero_profiles
  for insert with check (auth.uid() = user_id);

-- Quests: Everyone can view quests
create policy "Everyone can view quests" on quests
  for select using (true);

-- User Quests: Users can manage their own quests
create policy "Users can view own quests" on user_quests
  for select using (auth.uid() = user_id);

create policy "Users can insert own quests" on user_quests
  for insert with check (auth.uid() = user_id);

create policy "Users can update own quests" on user_quests
  for update using (auth.uid() = user_id);

-- Inserir algumas quests iniciais
insert into quests (title, description, xp_reward, attribute_reward, type) values
('Primeiro Passo', 'Faça seu primeiro check-in diário.', 50, 'resilience', 'story'),
('Mente Serena', 'Complete uma sessão de Mindfulness.', 30, 'focus', 'daily'),
('Conexão Humana', 'Participe de uma Roda de Conversa.', 40, 'empathy', 'daily'),
('Aprendiz', 'Leia um artigo na área de Estudos.', 20, 'wisdom', 'daily');
