-- Sistema Social Completo - Fase 3: Comunidades (Orkut-style)

-- ===============================
-- 1. COMUNIDADES
-- ===============================

create table communities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text not null check (category in ('mental_health', 'wellness', 'support', 'hobbies', 'general')),
  cover_image_url text,
  owner_id uuid references auth.users not null,
  is_public boolean default true,
  requires_approval boolean default false,
  member_count int default 1,
  post_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ===============================
-- 2. MEMBROS DA COMUNIDADE
-- ===============================

create table community_members (
  id bigint generated by default as identity primary key,
  community_id bigint references communities(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  role text default 'member' check (role in ('owner', 'moderator', 'member')),
  status text default 'approved' check (status in ('pending', 'approved', 'banned')),
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(community_id, user_id)
);

-- ===============================
-- 3. POSTS EM COMUNIDADES
-- ===============================

create table community_posts (
  id bigint generated by default as identity primary key,
  community_id bigint references communities(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  title text not null,
  content text not null,
  likes int default 0,
  comments int default 0,
  is_pinned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ===============================
-- 4. COMENTÁRIOS EM POSTS DE COMUNIDADES
-- ===============================

create table community_post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references community_posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  content text not null,
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ===============================
-- 5. CURTIDAS EM POSTS DE COMUNIDADES
-- ===============================

create table community_post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint references community_posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id)
);

-- ===============================
-- 6. CONFIGURAÇÕES DA COMUNIDADE
-- ===============================

create table community_settings (
  id bigint generated by default as identity primary key,
  community_id bigint references communities(id) on delete cascade not null unique,
  allow_posts boolean default true,
  allow_comments boolean default true,
  require_post_approval boolean default false,
  custom_colors jsonb default '{"primary": "#B026FF", "secondary": "#10B981"}'::jsonb,
  welcome_message text,
  rules text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Índices para performance
create index community_members_community_id_idx on community_members(community_id);
create index community_members_user_id_idx on community_members(user_id);
create index community_posts_community_id_idx on community_posts(community_id);
create index community_post_comments_post_id_idx on community_post_comments(post_id);

-- ===============================
-- 7. RLS POLICIES
-- ===============================

-- Communities
alter table communities enable row level security;

create policy "Public communities are viewable by everyone" on communities
  for select using (is_public = true);

create policy "Members can view private communities" on communities
  for select using (
    not is_public and exists(
      select 1 from community_members
      where community_id = id
      and user_id = auth.uid()
      and status = 'approved'
    )
  );

create policy "Authenticated users can create communities" on communities
  for insert with check (auth.uid() = owner_id);

create policy "Owners can update their communities" on communities
  for update using (auth.uid() = owner_id);

create policy "Owners can delete their communities" on communities
  for delete using (auth.uid() = owner_id);

-- Community Members
alter table community_members enable row level security;

create policy "Members can view other members in their communities" on community_members
  for select using (
    exists(
      select 1 from community_members cm
      where cm.community_id = community_id
      and cm.user_id = auth.uid()
      and cm.status = 'approved'
    )
  );

create policy "Users can join communities" on community_members
  for insert with check (auth.uid() = user_id);

create policy "Moderators can update members" on community_members
  for update using (
    exists(
      select 1 from community_members cm
      where cm.community_id = community_id
      and cm.user_id = auth.uid()
      and cm.role in ('owner', 'moderator')
      and cm.status = 'approved'
    )
  );

-- Community Posts
alter table community_posts enable row level security;

create policy "Members can view posts in their communities" on community_posts
  for select using (
    exists(
      select 1 from communities c
      left join community_members cm on c.id = cm.community_id and cm.user_id = auth.uid()
      where c.id = community_id
      and (c.is_public or (cm.status = 'approved'))
    )
  );

create policy "Approved members can create posts" on community_posts
  for insert with check (
    auth.uid() = user_id and
    exists(
      select 1 from community_members cm
      join community_settings cs on cm.community_id = cs.community_id
      where cm.community_id = community_posts.community_id
      and cm.user_id = auth.uid()
      and cm.status = 'approved'
      and cs.allow_posts = true
    )
  );

create policy "Users can update their own posts" on community_posts
  for update using (auth.uid() = user_id);

create policy "Users can delete their own posts" on community_posts
  for delete using (auth.uid() = user_id);

-- Community Post Comments
alter table community_post_comments enable row level security;

create policy "Users can view comments on posts they can see" on community_post_comments
  for select using (
    exists(
      select 1 from community_posts cp
      join communities c on cp.community_id = c.id
      left join community_members cm on c.id = cm.community_id and cm.user_id = auth.uid()
      where cp.id = post_id
      and (c.is_public or (cm.status = 'approved'))
    )
  );

create policy "Members can comment on posts" on community_post_comments
  for insert with check (
    auth.uid() = user_id and
    exists(
      select 1 from community_posts cp
      join community_members cm on cp.community_id = cm.community_id
      join community_settings cs on cp.community_id = cs.community_id
      where cp.id = post_id
      and cm.user_id = auth.uid()
      and cm.status = 'approved'
      and cs.allow_comments = true
    )
  );

-- Community Post Likes
alter table community_post_likes enable row level security;

create policy "Users can view likes" on community_post_likes
  for select using (true);

create policy "Users can like posts" on community_post_likes
  for insert with check (auth.uid() = user_id);

create policy "Users can unlike posts" on community_post_likes
  for delete using (auth.uid() = user_id);

-- Community Settings
alter table community_settings enable row level security;

create policy "Members can view community settings" on community_settings
  for select using (
    exists(
      select 1 from community_members cm
      where cm.community_id = community_id
      and cm.user_id = auth.uid()
      and cm.status = 'approved'
    )
  );

create policy "Owners and moderators can update settings" on community_settings
  for update using (
    exists(
      select 1 from community_members cm
      where cm.community_id = community_id
      and cm.user_id = auth.uid()
      and cm.role in ('owner', 'moderator')
      and cm.status = 'approved'
    )
  );

-- ===============================
-- 8. FUNCTIONS
-- ===============================

-- Criar comunidade
create or replace function create_community(
  p_name text,
  p_description text,
  p_category text,
  p_is_public boolean default true,
  p_requires_approval boolean default false
)
returns bigint
language plpgsql
security definer
as $$
declare
  v_community_id bigint;
begin
  -- Criar comunidade
  insert into communities (name, description, category, owner_id, is_public, requires_approval)
  values (p_name, p_description, p_category, auth.uid(), p_is_public, p_requires_approval)
  returning id into v_community_id;

  -- Adicionar owner como membro
  insert into community_members (community_id, user_id, role, status)
  values (v_community_id, auth.uid(), 'owner', 'approved');

  -- Criar configurações padrão
  insert into community_settings (community_id)
  values (v_community_id);

  return v_community_id;
end;
$$;

-- Entrar na comunidade
create or replace function join_community(p_community_id bigint)
returns void
language plpgsql
security definer
as $$
declare
  v_requires_approval boolean;
  v_status text;
begin
  -- Verificar se requer aprovação
  select requires_approval into v_requires_approval
  from communities
  where id = p_community_id;

  if not found then
    raise exception 'Community not found';
  end if;

  -- Definir status baseado em aprovação
  v_status := case when v_requires_approval then 'pending' else 'approved' end;

  -- Adicionar membro
  insert into community_members (community_id, user_id, status)
  values (p_community_id, auth.uid(), v_status)
  on conflict (community_id, user_id) do nothing;

  -- Incrementar contador se aprovado
  if v_status = 'approved' then
    update communities
    set member_count = member_count + 1
    where id = p_community_id;
  end if;
end;
$$;

-- Aprovar membro
create or replace function approve_member(
  p_community_id bigint,
  p_user_id uuid
)
returns void
language plpgsql
security definer
as $$
begin
  -- Verificar se é moderador
  if not exists(
    select 1 from community_members
    where community_id = p_community_id
    and user_id = auth.uid()
    and role in ('owner', 'moderator')
    and status = 'approved'
  ) then
    raise exception 'Not authorized';
  end if;

  -- Aprovar membro
  update community_members
  set status = 'approved'
  where community_id = p_community_id
  and user_id = p_user_id;

  -- Incrementar contador
  update communities
  set member_count = member_count + 1
  where id = p_community_id;

  -- Criar notificação
  insert into notifications (user_id, type, title, reference_type, reference_id)
  values (
    p_user_id,
    'community_invite',
    'Aprovado na comunidade',
    'community',
    p_community_id
  );
end;
$$;

-- Buscar comunidades populares
create or replace function get_popular_communities(p_limit int default 10)
returns table(
  id bigint,
  name text,
  description text,
  category text,
  member_count int,
  post_count int,
  cover_image_url text
)
language sql
security definer
as $$
  select
    id,
    name,
    description,
    category,
    member_count,
    post_count,
    cover_image_url
  from communities
  where is_public = true
  order by member_count desc, post_count desc
  limit p_limit;
$$;

-- Buscar minhas comunidades
create or replace function get_my_communities(p_user_id uuid)
returns table(
  id bigint,
  name text,
  description text,
  category text,
  member_count int,
  post_count int,
  cover_image_url text,
  role text,
  unread_posts int
)
language sql
security definer
as $$
  select
    c.id,
    c.name,
    c.description,
    c.category,
    c.member_count,
    c.post_count,
    c.cover_image_url,
    cm.role,
    0 as unread_posts
  from communities c
  join community_members cm on c.id = cm.community_id
  where cm.user_id = p_user_id
  and cm.status = 'approved'
  order by cm.joined_at desc;
$$;

-- ===============================
-- 9. TRIGGERS
-- ===============================

-- Atualizar contador de posts
create or replace function update_community_post_count()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'INSERT' then
    update communities
    set post_count = post_count + 1
    where id = NEW.community_id;
  elsif TG_OP = 'DELETE' then
    update communities
    set post_count = post_count - 1
    where id = OLD.community_id;
  end if;
  return NEW;
end;
$$;

create trigger community_post_count_trigger
after insert or delete on community_posts
for each row
execute function update_community_post_count();

-- Atualizar contador de comentários em posts de comunidade
create or replace function update_community_post_comments_count()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'INSERT' then
    update community_posts
    set comments = comments + 1
    where id = NEW.post_id;
  elsif TG_OP = 'DELETE' then
    update community_posts
    set comments = comments - 1
    where id = OLD.post_id;
  end if;
  return NEW;
end;
$$;

create trigger community_post_comments_count_trigger
after insert or delete on community_post_comments
for each row
execute function update_community_post_comments_count();

-- Atualizar contador de likes em posts de comunidade
create or replace function update_community_post_likes_count()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'INSERT' then
    update community_posts
    set likes = likes + 1
    where id = NEW.post_id;
  elsif TG_OP = 'DELETE' then
    update community_posts
    set likes = likes - 1
    where id = OLD.post_id;
  end if;
  return NEW;
end;
$$;

create trigger community_post_likes_count_trigger
after insert or delete on community_post_likes
for each row
execute function update_community_post_likes_count();
