-- Sistema Social Completo - Fase 1
-- Upload de fotos, Amizades e Moderação

-- ===============================
-- 0. PREPARAÇÃO - Adicionar colunas necessárias PRIMEIRO
-- ===============================

-- Adicionar coluna role ao profiles se não existir (ANTES de criar policies)
alter table profiles add column if not exists role text default 'user' check (role in ('user', 'moderator', 'admin'));

-- Adicionar colunas de perfil estendido
alter table profiles add column if not exists bio text;

-- Solicitações de amizade
create table friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(sender_id, receiver_id),
  check (sender_id != receiver_id)
);

-- Amizades confirmadas
create table friendships (
  id bigint generated by default as identity primary key,
  user_id_1 uuid references auth.users not null,
  user_id_2 uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id_1, user_id_2),
  check (user_id_1 < user_id_2) -- Garantir ordem consistente
);

-- ===============================
-- 2. SISTEMA DE MODERAÇÃO
-- ===============================

-- Reputação e punições do usuário
create table user_reputation (
  user_id uuid references auth.users primary key,
  reputation_score int default 100,
  strikes_count int default 0,
  is_banned boolean default false,
  ban_until timestamp with time zone,
  restrictions jsonb default '{"can_post": true, "can_comment": true, "can_like": true, "can_message": true, "can_join_communities": true, "can_create_communities": true}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ações de moderação
create table moderation_actions (
  id bigint generated by default as identity primary key,
  target_user_id uuid references auth.users not null,
  moderator_id uuid references auth.users,
  action_type text not null check (action_type in ('warning', 'strike', 'temp_ban', 'permanent_ban', 'restriction')),
  reason text not null,
  duration_days int,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Denúncias de conteúdo
create table content_flags (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('post', 'comment', 'message', 'profile', 'community')),
  content_id bigint not null,
  reporter_id uuid references auth.users not null,
  flag_type text not null check (flag_type in ('offensive', 'racism', 'sexism', 'lgbtphobia', 'harassment', 'spam', 'other')),
  description text,
  status text default 'pending' check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  moderator_id uuid references auth.users,
  moderator_notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone
);

-- ===============================
-- 3. PERFIL ESTENDIDO
-- ===============================

-- Adicionar colunas ao profiles existente
alter table profiles add column if not exists bio text;
alter table profiles add column if not exists location text;
alter table profiles add column if not exists website text;
alter table profiles add column if not exists interests text[];
alter table profiles add column if not exists pronouns text;
alter table profiles add column if not exists privacy_settings jsonb default '{"profile_public": true, "allow_messages_from": "everyone", "show_friends": true}'::jsonb;
alter table profiles add column if not exists last_active_at timestamp with time zone default timezone('utc'::text, now());

-- ===============================
-- 4. STORAGE (Configurar via Supabase UI)
-- ===============================
-- Criar bucket 'avatars' no Supabase Storage
-- Políticas: público para leitura, autenticado para upload

-- ===============================
-- 5. RLS POLICIES
-- ===============================

-- Friend Requests
alter table friend_requests enable row level security;

create policy "Users can view their own friend requests" on friend_requests
  for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can send friend requests" on friend_requests
  for insert with check (auth.uid() = sender_id);

create policy "Users can update received requests" on friend_requests
  for update using (auth.uid() = receiver_id);

-- Friendships
alter table friendships enable row level security;

create policy "Users can view friendships they're part of" on friendships
  for select using (auth.uid() = user_id_1 or auth.uid() = user_id_2);

create policy "System can insert friendships" on friendships
  for insert with check (true); -- Controlado por função

-- User Reputation
alter table user_reputation enable row level security;

create policy "Users can view their own reputation" on user_reputation
  for select using (auth.uid() = user_id);

create policy "Moderators can view all reputations" on user_reputation
  for select using (exists(
    select 1 from profiles where id = auth.uid() and role = 'moderator'
  ));

-- Moderation Actions
alter table moderation_actions enable row level security;

create policy "Users can view actions against them" on moderation_actions
  for select using (auth.uid() = target_user_id);

create policy "Moderators can view all actions" on moderation_actions
  for select using (exists(
    select 1 from profiles where id = auth.uid() and role = 'moderator'
  ));

-- Content Flags
alter table content_flags enable row level security;

create policy "Users can create flags" on content_flags
  for insert with check (auth.uid() = reporter_id);

create policy "Users can view their own flags" on content_flags
  for select using (auth.uid() = reporter_id);

create policy "Moderators can view all flags" on content_flags
  for select using (exists(
    select 1 from profiles where id = auth.uid() and role = 'moderator'
  ));

-- ===============================
-- 6. FUNCTIONS
-- ===============================

-- Aceitar solicitação de amizade
create or replace function accept_friend_request(p_request_id bigint)
returns void
language plpgsql
security definer
as $$
declare
  v_sender_id uuid;
  v_receiver_id uuid;
begin
  -- Buscar IDs
  select sender_id, receiver_id into v_sender_id, v_receiver_id
  from friend_requests
  where id = p_request_id and receiver_id = auth.uid();

  if not found then
    raise exception 'Friend request not found or not authorized';
  end if;

  -- Atualizar request
  update friend_requests
  set status = 'accepted', updated_at = now()
  where id = p_request_id;

  -- Criar amizade (garantir ordem consistente)
  insert into friendships (user_id_1, user_id_2)
  values (least(v_sender_id, v_receiver_id), greatest(v_sender_id, v_receiver_id))
  on conflict do nothing;
end;
$$;

-- Aplicar strike
create or replace function apply_strike(
  p_user_id uuid,
  p_reason text,
  p_moderator_id uuid default null
)
returns void
language plpgsql
security definer
as $$
declare
  v_current_strikes int;
  v_new_restrictions jsonb;
  v_ban_until timestamp;
begin
  -- Buscar strikes atuais
  select strikes_count into v_current_strikes
  from user_reputation
  where user_id = p_user_id;

  if not found then
    -- Criar registro de reputação
    insert into user_reputation (user_id, strikes_count)
    values (p_user_id, 0);
    v_current_strikes := 0;
  end if;

  -- Incrementar strikes
  v_current_strikes := v_current_strikes + 1;

  -- Aplicar punição baseada no número de strikes
  case v_current_strikes
    when 1 then
      -- Strike 1: Aviso + 24h sem comentar
      v_new_restrictions := '{"can_post": true, "can_comment": false, "can_like": true, "can_message": true, "can_join_communities": true, "can_create_communities": true}'::jsonb;
      v_ban_until := now() + interval '1 day';
    when 2 then
      -- Strike 2: 3 dias sem postar
      v_new_restrictions := '{"can_post": false, "can_comment": false, "can_like": true, "can_message": true, "can_join_communities": true, "can_create_communities": true}'::jsonb;
      v_ban_until := now() + interval '3 days';
    when 3 then
      -- Strike 3: 7 dias sem interagir
      v_new_restrictions := '{"can_post": false, "can_comment": false, "can_like": false, "can_message": true, "can_join_communities": false, "can_create_communities": false}'::jsonb;
      v_ban_until := now() + interval '7 days';
    when 4 then
      -- Strike 4: Ban 30 dias
      v_new_restrictions := '{"can_post": false, "can_comment": false, "can_like": false, "can_message": false, "can_join_communities": false, "can_create_communities": false}'::jsonb;
      v_ban_until := now() + interval '30 days';
      update user_reputation set is_banned = true where user_id = p_user_id;
    else
      -- Strike 5+: Ban permanente
      v_new_restrictions := '{"can_post": false, "can_comment": false, "can_like": false, "can_message": false, "can_join_communities": false, "can_create_communities": false}'::jsonb;
      v_ban_until := now() + interval '100 years';
      update user_reputation set is_banned = true where user_id = p_user_id;
  end case;

  -- Atualizar reputação
  update user_reputation
  set strikes_count = v_current_strikes,
      restrictions = v_new_restrictions,
      ban_until = v_ban_until,
      reputation_score = greatest(0, reputation_score - 20),
      updated_at = now()
  where user_id = p_user_id;

  -- Registrar ação de moderação
  insert into moderation_actions (target_user_id, moderator_id, action_type, reason, duration_days)
  values (p_user_id, p_moderator_id, 'strike', p_reason, extract(day from (v_ban_until - now()))::int);
end;
$$;

-- Buscar amigos
create or replace function get_friends(p_user_id uuid)
returns table(
  friend_id uuid,
  username text,
  full_name text,
  avatar_url text,
  last_active_at timestamp with time zone
)
language sql
security definer
as $$
  select 
    case 
      when f.user_id_1 = p_user_id then f.user_id_2
      else f.user_id_1
    end as friend_id,
    p.username,
    p.full_name,
    p.avatar_url,
    p.last_active_at
  from friendships f
  join profiles p on (
    case 
      when f.user_id_1 = p_user_id then f.user_id_2
      else f.user_id_1
    end = p.id
  )
  where f.user_id_1 = p_user_id or f.user_id_2 = p_user_id
  order by p.last_active_at desc nulls last;
$$;

-- Verificar se são amigos
create or replace function are_friends(p_user_id_1 uuid, p_user_id_2 uuid)
returns boolean
language sql
security definer
as $$
  select exists(
    select 1 from friendships
    where (user_id_1 = least(p_user_id_1, p_user_id_2) and user_id_2 = greatest(p_user_id_1, p_user_id_2))
  );
$$;
