-- Migration: Add level and xp to profiles, create posts and chat_messages tables

-- Add columns to profiles
alter table profiles
  add column level int default 1,
  add column xp int default 0;

alter table profiles enable row level security;
create policy "Profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update their own profile (including level/xp)" on profiles for update with check (auth.uid() = id);

-- Create posts table
create table posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text not null,
  avatar_url text,
  content text not null,
  likes int default 0,
  comments int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table posts enable row level security;
create policy "Posts are viewable by everyone" on posts for select using (true);
create policy "Users can insert their own posts" on posts for insert with check (auth.uid() = user_id);
create policy "Users can like posts" on posts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Create chat_messages table
create table chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  type text check (type in ('user','bot')) not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table chat_messages enable row level security;
create policy "Chat messages are viewable by everyone" on chat_messages for select using (true);
create policy "Users can insert their own messages" on chat_messages for insert with check (auth.uid() = user_id or user_id is null);
