-- Create meditations table
create table meditations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  duration_seconds integer not null,
  category text, -- e.g., 'Foco', 'Sono', 'Calma'
  audio_url text -- Optional for now, can use placeholder
);

-- Create panic_logs table (for LibertaMente usage)
create table panic_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tool_used text not null, -- e.g., 'breathing_478', 'grounding_54321'
  duration_seconds integer,
  notes text
);

-- Create meditation_logs table (for Mindfulness history)
create table meditation_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  meditation_id bigint references meditations(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  duration_listened_seconds integer not null
);

-- Enable RLS
alter table meditations enable row level security;
alter table panic_logs enable row level security;
alter table meditation_logs enable row level security;

-- RLS Policies
create policy "Meditations are viewable by everyone." on meditations for select using (true);

create policy "Users can view their own panic logs." on panic_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own panic logs." on panic_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can view their own meditation logs." on meditation_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own meditation logs." on meditation_logs
  for insert with check (auth.uid() = user_id);

-- Seed Meditations
insert into meditations (title, description, duration_seconds, category) values
('Respiração Consciente', 'Foque na sua respiração para acalmar a mente.', 300, 'Foco'),
('Relaxamento Profundo', 'Relaxe cada músculo do seu corpo.', 600, 'Sono'),
('Alívio de Ansiedade', 'Técnicas para reduzir a ansiedade no momento.', 900, 'Calma');
